import { useState, type FormEvent } from 'react';
import { Bell, Check, Download, KeyRound, Pause, Plus, Settings2, ShieldCheck, Target, Trash2 } from 'lucide-react';
import { useWorkspace } from '../lib/WorkspaceContext';
import { displayDate, localDate, money, parseMoney, type Currency, type Goal } from '../lib/workspace';
import { EmptyState, Field, Modal, PageHeading, Panel, useToast } from '../components/ui';
import type { Config } from '../types';
import { api } from '../lib/api';

export default function Settings() {
  const { state, command, accessMode } = useWorkspace(), toast = useToast();
  const [profile, setProfile] = useState({...state.profile}), [saving,setSaving] = useState(false), [error,setError] = useState(''), [goal,setGoal] = useState<Partial<Goal>|null>(null), [goalTarget,setGoalTarget] = useState(''), [config,setConfig] = useState<Config|null>(null), [checking,setChecking] = useState(false);
  const save = async (event:FormEvent) => { event.preventDefault(); setError(''); setSaving(true); try { await command('profile.save',profile); toast('Configurações salvas.'); } catch(e) { setError(e instanceof Error?e.message:'Não foi possível salvar.'); } finally {setSaving(false);} };
  const requestNotifications = async () => {setError(''); if(!('Notification' in window)){setError('Este navegador não oferece notificações.');return;} const permission=await Notification.requestPermission(); if(permission==='granted'){setProfile({...profile,browserNotifications:true});toast('Permissão concedida. Salve suas preferências para ativar.');} else setError('O navegador não autorizou as notificações. Você pode continuar usando a central de avisos.');};
  const saveGoal = async(event:FormEvent) => {event.preventDefault();setError('');setSaving(true);try {const target=goal?.kind==='activities'?Number(goalTarget):parseMoney(goalTarget);if(!Number.isSafeInteger(target)||target<=0)throw new Error('Informe uma meta maior que zero.');await command('goal.save',{...goal,target});setGoal(null);toast('Meta salva.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a meta.');}finally{setSaving(false);}};
  const removeGoal = async(id:string) => {if(!window.confirm('Remover esta meta? Os registros financeiros serão preservados.'))return;try{await command('goal.delete',{id});toast('Meta removida.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover.');}};
  const checkConfig = async() => {setChecking(true);setError('');try{setConfig(await api<Config>('/api/config'));}catch(e){setError(e instanceof Error?e.message:'Não foi possível verificar.');}finally{setChecking(false);}};
  const exportData=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='the-ghost-meus-dados-'+localDate(state.profile.timezone)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Seus dados foram exportados.');};
  return <div><PageHeading eyebrow="DO SEU JEITO" title="Configurações" description="Sua identidade, suas metas e suas preferências."/>
    {error&&!goal&&<div className="error-message" role="alert">{error}</div>}
    <div className="settings-grid">
      <Panel title="Perfil e preferências"><form onSubmit={save}><div className="form-grid"><Field label="Seu nome"><input required maxLength={120} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} autoComplete="name"/></Field>{accessMode==='accounts'&&<Field label="E-mail de acesso"><input value={profile.email} readOnly type="email" aria-describedby="identity-note"/></Field>}<Field label="Fuso horário"><select value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})}>{['America/Sao_Paulo','Europe/Madrid','Europe/Rome','America/New_York','America/Los_Angeles','Europe/Amsterdam','UTC'].map(zone=><option key={zone}>{zone}</option>)}</select></Field><Field label="Moeda inicial"><select value={profile.currency} onChange={e=>setProfile({...profile,currency:e.target.value as Currency})}><option value="BRL">BRL · Real brasileiro</option><option value="EUR">EUR · Euro</option><option value="USD">USD · Dólar americano</option></select></Field></div><p id="identity-note" className="muted">Datas e indicadores de hoje seguem o fuso selecionado. Seu nome pode ser personalizado aqui.</p><div className="preference-list"><label><div><Pause size={19}/><span><b>Pausar efeitos contínuos</b><small>Globo e partículas ficam estáticos.</small></span></div><input type="checkbox" checked={profile.paused} onChange={e=>setProfile({...profile,paused:e.target.checked})}/></label><label><div><Bell size={19}/><span><b>Avisos sonoros</b><small>Um toque discreto para novas notificações.</small></span></div><input type="checkbox" checked={profile.soundNotifications} onChange={e=>setProfile({...profile,soundNotifications:e.target.checked})}/></label><div className="preference-row"><div><Bell size={19}/><span><b>Notificações do navegador</b><small>Somente eventos reais da sua conta enquanto o site estiver aberto.</small></span></div>{profile.browserNotifications?<button className="text-button" type="button" onClick={()=>setProfile({...profile,browserNotifications:false})}>Desativar</button>:<button className="button button-secondary" type="button" onClick={()=>void requestNotifications()}>Autorizar</button>}</div></div><div className="form-actions"><button className="button button-primary" disabled={saving}><Check size={17}/>{saving?'Salvando…':'Salvar preferências'}</button></div></form></Panel>
      <div className="settings-side"><Panel title="Integrações" action={<KeyRound size={18}/>}><p className="muted">Confira a configuração do servidor. Credenciais privadas são adicionadas nas variáveis de ambiente da hospedagem.</p><div className="integration-status"><div><span>Google Places</span><span className={'badge '+(config?.placesEnabled&&config.liveSearchAllowed?'success':'')}>{config?config.placesEnabled?config.liveSearchAllowed?'Configurado':'Revisão de uso pendente':'Não configurado':'Não verificado'}</span></div><div><span>Geração com IA</span><span className={'badge '+(config?.aiEnabled?'success':'')}>{config?config.aiEnabled?'Configurada':'Modelos locais disponíveis':'Não verificado'}</span></div></div><button className="button button-secondary" onClick={()=>void checkConfig()} disabled={checking}>{checking?'Verificando…':'Verificar configuração'}</button><p className="muted small-copy">Status de configuração não comprova uma consulta bem-sucedida ao provedor. CRM e financeiro funcionam com seus registros próprios.</p></Panel><Panel title="Seus dados" action={<ShieldCheck size={18}/>}><p className="muted">Exporte seus cadastros e registros da conta em JSON. O arquivo contém suas informações comerciais e financeiras.</p><button className="button button-secondary" onClick={exportData}><Download size={16}/>Baixar meus dados</button></Panel></div>
    </div>
    <Panel title="Metas" action={<button className="button button-secondary" onClick={()=>{setError('');setGoal({name:'',kind:'sales',currency:state.profile.currency,startDate:localDate(state.profile.timezone),endDate:localDate(state.profile.timezone)});setGoalTarget('');}}><Plus size={16}/>Criar meta</button>}>{state.goals.length?<div className="goal-settings-list">{state.goals.map(item=><div key={item.id}><Target size={20}/><div><b>{item.name}</b><span>{item.kind==='activities'?item.target+' atividades':money(item.target,item.currency)} · {displayDate(item.startDate)} a {displayDate(item.endDate)}</span></div><button className="icon-button" aria-label={'Editar meta '+item.name} onClick={()=>{setGoal(item);setGoalTarget(item.kind==='activities'?String(item.target):(item.target/100).toFixed(2));setError('');}}><Settings2 size={17}/></button><button className="icon-button" aria-label={'Remover meta '+item.name} onClick={()=>void removeGoal(item.id)}><Trash2 size={17}/></button></div>)}</div>:<EmptyState icon={Target} title="Seu próximo objetivo" description="Defina uma meta de vendas, recebimentos ou atividades para acompanhar seu progresso."/>}</Panel>
    {goal&&<Modal title={goal.id?'Editar meta':'Criar meta'} onClose={()=>setGoal(null)}><form onSubmit={saveGoal}><Field label="Nome da meta"><input required maxLength={150} value={goal.name||''} onChange={e=>setGoal({...goal,name:e.target.value})}/></Field><div className="form-grid"><Field label="Indicador"><select value={goal.kind} onChange={e=>{setGoal({...goal,kind:e.target.value as Goal['kind']});setGoalTarget('');}}><option value="sales">Valor vendido</option><option value="receipts">Valor recebido líquido</option><option value="activities">Quantidade de atividades</option></select></Field><Field label={goal.kind==='activities'?'Quantidade':'Valor da meta'}><input required inputMode={goal.kind==='activities'?'numeric':'decimal'} value={goalTarget} onChange={e=>setGoalTarget(e.target.value)}/></Field>{goal.kind!=='activities'&&<Field label="Moeda"><select value={goal.currency} onChange={e=>setGoal({...goal,currency:e.target.value as Currency})}><option>BRL</option><option>EUR</option><option>USD</option></select></Field>}<Field label="Início"><input type="date" required value={goal.startDate} onChange={e=>setGoal({...goal,startDate:e.target.value})}/></Field><Field label="Fim"><input type="date" required min={goal.startDate} value={goal.endDate} onChange={e=>setGoal({...goal,endDate:e.target.value})}/></Field></div>{error&&<div className="error-message" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={()=>setGoal(null)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving?'Salvando…':'Salvar meta'}</button></div></form></Modal>}
  </div>;
}
